# -*- coding: utf-8 -*-
"""DLBasics2025_competition_EEG_conformer_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzQQRG6DPbgGKaAq_p2TQRy7TWikYzoD

# Deep Learning 基礎講座　最終課題: 脳波分類

## 概要
被験者が画像を見ているときの脳波から，その画像がどのカテゴリに属するかを分類するタスク．
- サンプル数: 訓練 118,800 サンプル，検証 59,400 サンプル，テスト 59,400 サンプル
- クラス数: 5
- 入力: 脳波データ（チャンネル数 x 系列長）
- 出力: 対応する画像のクラス
- 評価指標: Top-1 accuracy

### 元データセット ([Gifford2022 EEG dataset](https://osf.io/3jk45/)) との違い

- 本コンペでは難易度調整の目的で元データセットにいくつかの改変を加えています．

1. 訓練セットのみの使用
  - 元データセットでは訓練データに存在しなかったクラスの画像を見ているときの脳波においてテストが行われますが，これは難易度が非常に高くなります．
  - 本コンペでは元データセットの訓練セットを再分割し，訓練時に存在した画像に対応する別の脳波において検証・テストを行います．

2. クラス数の減少
  - 元データセット（の訓練セット）では16,540枚の画像に対し，1,654のクラスが存在します．
    - e.g. `aardvark`, `alligator`, `almond`, ...
  - 本コンペでは1,654のクラスを，`animal`, `food`, `clothing`, `tool`, `vehicle`の5つにまとめています．
    - e.g. `aardvark -> animal`, `alligator -> animal`, `almond -> food`, ...

### 考えられる工夫の例

- 音声モデルの導入
  - 脳波と同じ波である音声を扱うアーキテクチャを用いることが有効であると知られています．
  - 例）Conformer [[Gulati+ 2020](https://arxiv.org/abs/2005.08100)]
- 画像データを用いた事前学習
  - 本コンペのタスクは脳波のクラス分類ですが，配布してある画像データを脳波エンコーダの事前学習に用いることを許可します．
  - 例）CLIP [Radford+ 2021]
  - 画像を用いる場合は[こちら](https://osf.io/download/3v527/)からダウンロードしてください．
- 過学習を防ぐ正則化やドロップアウト

## 修了要件を満たす条件
- ベースラインモデルのbest test accuracyは38.7%となります．**これを超えた提出のみ，修了要件として認めます**．
- ベースラインから改善を加えることで，55%までは性能向上することを運営で確認しています．こちらを 1 つの指標として取り組んでみてください．

## 注意点
- 学習するモデルについて制限はありませんが，必ず訓練データで学習したモデルで予測してください．
    - 事前学習済みモデルを利用して，訓練データを fine-tuning しても構いません．
    - 埋め込み抽出モデルなど，モデルの一部を訓練しないケースは構いません．
    - 学習を一切せずに，ChatGPT などの基盤モデルを利用することは禁止とします．

## 1.準備
"""

# omnicampus 実行用
!pip install ipywidgets
!pip install transformers
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# ライブラリのインポートとシード固定
import os, sys
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter
from einops.layers.torch import Rearrange
from einops import repeat
from glob import glob
from termcolor import cprint
from tqdm.notebook import tqdm
from sklearn.model_selection import KFold
import math
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
from collections import defaultdict
from typing import Optional
from torchvision.models import resnet18, ResNet18_Weights

SEED = 0
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ドライブのマウント（Colabの場合）
# from google.colab import drive
# drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# ワーキングディレクトリを作成し移動．ノートブックを配置したディレクトリに適宜書き換え
WORK_DIR = "/workspace/assets"
# WORK_DIR = '/content/drive/MyDrive/DLBasic/final_project'
os.makedirs(WORK_DIR, exist_ok=True)
# %cd {WORK_DIR}

"""## 2.データセット

ノートブックと同じディレクトリに`data/`が存在することを確認してください．
"""

class EEGAugmentation:
    def __init__(self, p=0.6):
        self.p = p

    def __call__(self, x):
        if random.random() > self.p:
            return x

        x = self.temporal_jittering(x)
        x = self.channel_dropout(x)
        x = self.gaussian_noise(x)
        x = self.amplitude_scaling(x)
        x = self.time_masking(x)

        return x

    def temporal_jittering(self, x, max_shift=3):
        if random.random() > 0.4:
            shift = random.randint(-max_shift, max_shift)
            if shift > 0:
                if x.dim() == 2:  # (channels, time)
                    x = F.pad(x, (shift, 0))[:, :-shift]
                elif x.dim() == 3:  # (batch, channels, time)
                    x = F.pad(x, (shift, 0))[:, :, :-shift]
            elif shift < 0:
                if x.dim() == 2:  # (channels, time)
                    x = F.pad(x, (0, -shift))[:, -shift:]
                elif x.dim() == 3:  # (batch, channels, time)
                    x = F.pad(x, (0, -shift))[:, :, -shift:]
        return x
    def channel_dropout(self, x, p=0.08):
        if random.random() > 0.3:
            if x.dim() == 2:  # (channels, time)
                num_channels = x.shape[0]
                mask = torch.rand(num_channels) > p
                x = x * mask.unsqueeze(-1)
            elif x.dim() == 3:  # (batch, channels, time)
                num_channels = x.shape[1]
                mask = torch.rand(num_channels) > p
                x = x * mask.unsqueeze(0).unsqueeze(-1)
        return x

    def gaussian_noise(self, x, std=0.015):
        if random.random() > 0.4:
            noise = torch.randn_like(x) * std
            x = x + noise
        return x

    def amplitude_scaling(self, x, scale_range=(0.85, 1.15)):
        if random.random() > 0.4:
            scale = random.uniform(*scale_range)
            x = x * scale
        return x

    def time_masking(self, x, max_mask_size=8):
        if random.random() > 0.5:
            seq_len = x.shape[-1]
            mask_size = random.randint(1, min(max_mask_size, seq_len // 12))
            mask_start = random.randint(0, seq_len - mask_size)
            if x.dim() == 2:  # (channels, time)
                x[:, mask_start:mask_start + mask_size] = 0
            elif x.dim() == 3:  # (batch, channels, time)
                x[:, :, mask_start:mask_start + mask_size] = 0
        return x

class ThingsEEGDataset(torch.utils.data.Dataset):
    def __init__(self, split: str, apply_whitening: bool = False, normalize_per_subject: bool = True, augment: bool = False, fold_indices: Optional[np.ndarray] = None) -> None:
        super().__init__()
        assert split in ["train", "val", "test"], f"Invalid split: {split}"
        self.split = split
        self.num_classes = 5
        self.num_subjects = 10
        self.normalize_per_subject = normalize_per_subject
        self.augment = augment and split == "train"

        self.X = np.load(f"EEG/{split}/eeg.npy")
        self.X = torch.from_numpy(self.X).to(torch.float32)
        self.subject_idxs = np.load(f"EEG/{split}/subject_idxs.npy")
        self.subject_idxs = torch.from_numpy(self.subject_idxs)

        if split in ["train", "val"]:
            self.y = np.load(f"EEG/{split}/labels.npy")
            self.y = torch.from_numpy(self.y)

        if fold_indices is not None:
            self.X = self.X[fold_indices]
            self.subject_idxs = self.subject_idxs[fold_indices]
            if hasattr(self, 'y'):
                self.y = self.y[fold_indices]

        # normalization
        if self.normalize_per_subject:
            self._normalize_per_subject()
        else:
            # normalization overall
            self.X = (self.X - self.X.mean(dim=-1, keepdim=True)) / (self.X.std(dim=-1, keepdim=True) + 1e-5)

        self.apply_whitening = apply_whitening
        if self.apply_whitening:
            self._apply_whitening()

        if self.augment:
            self.augmentation = EEGAugmentation(p=0.6)

        self.num_subjects = len(torch.unique(self.subject_idxs))
        print(f"EEG: {self.X.shape}, labels: {self.y.shape if hasattr(self, 'y') else None}, subject indices: {self.subject_idxs.shape}")
        print(f"Number of subjects: {self.num_subjects}")

    def _normalize_per_subject(self):
        for subject_id in torch.unique(self.subject_idxs):
            mask = self.subject_idxs == subject_id
            subject_data = self.X[mask]
            # channel-wise normalization
            mean = subject_data.mean(dim=(0, 2), keepdim=True)
            std = subject_data.std(dim=(0, 2), keepdim=True)
            self.X[mask] = (subject_data - mean) / (std + 1e-5)

    def _apply_whitening(self):
        X_flat = self.X.reshape(self.X.shape[0], -1).numpy()
        X_mean = X_flat.mean(axis=0, keepdims=True)
        X_centered = X_flat - X_mean
        cov = np.cov(X_centered, rowvar=False)

        U, S, Vt = np.linalg.svd(cov)

        S_clipped = np.maximum(S, 1e-3)
        self.whitening_matrix = torch.from_numpy(U @ np.diag(1.0 / np.sqrt(S_clipped)) @ U.T).to(torch.float32)
        self.X_mean = torch.from_numpy(X_mean).to(torch.float32)

    def __len__(self) -> int:
        return len(self.X)

    def __getitem__(self, i):
        X = self.X[i]
        if self.apply_whitening:
            X_flat = X.flatten()
            X_flat = X_flat - self.X_mean.squeeze()
            X_flat = torch.matmul(self.whitening_matrix, X_flat)
            X = X_flat.view_as(X)

        if self.augment:
            X = self.augmentation(X)

        if hasattr(self, "y"):
            return X, self.y[i], self.subject_idxs[i]
        else:
            return X, self.subject_idxs[i]

    @property
    def num_channels(self) -> int:
        return self.X.shape[1]

    @property
    def seq_len(self) -> int:
        return self.X.shape[2]

"""## 3.ベースラインモデル"""

# Conformer-inspired architecture for EEG data
class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        return self.linear2(self.dropout(F.relu(self.linear1(x))))

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads, dropout=0.1):
        super().__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)

        self.dropout = nn.Dropout(dropout)

    def scaled_dot_product_attention(self, Q, K, V, mask=None):
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)
        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)
        attention_weights = F.softmax(scores, dim=-1)
        attention_weights = self.dropout(attention_weights)
        output = torch.matmul(attention_weights, V)
        return output

    def forward(self, query, key, value, mask=None):
        batch_size = query.size(0)

        Q = self.W_q(query).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        K = self.W_k(key).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        V = self.W_v(value).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)

        attention = self.scaled_dot_product_attention(Q, K, V, mask)
        attention = attention.transpose(1, 2).contiguous().view(batch_size, -1, self.d_model)

        output = self.W_o(attention)
        return output

class ConvolutionModule(nn.Module):
    def __init__(self, d_model, kernel_size=31, dropout=0.1):
        super().__init__()
        self.pointwise_conv1 = nn.Conv1d(d_model, d_model * 2, kernel_size=1)
        self.depthwise_conv = nn.Conv1d(d_model, d_model, kernel_size=kernel_size,
                                       padding=(kernel_size - 1) // 2, groups=d_model)
        self.batch_norm = nn.BatchNorm1d(d_model)
        self.pointwise_conv2 = nn.Conv1d(d_model, d_model, kernel_size=1)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x: (batch, seq_len, d_model)
        x = x.transpose(1, 2)  # (batch, d_model, seq_len)

        x = self.pointwise_conv1(x)
        x = F.glu(x, dim=1)
        x = self.depthwise_conv(x)
        x = self.batch_norm(x)
        x = F.silu(x)
        x = self.pointwise_conv2(x)
        x = self.dropout(x)

        return x.transpose(1, 2)  # (batch, seq_len, d_model)

class ConformerBlock(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, conv_kernel_size=31, dropout=0.1):
        super().__init__()
        self.ff1 = FeedForward(d_model, d_ff, dropout)
        self.mha = MultiHeadAttention(d_model, num_heads, dropout)
        self.conv = ConvolutionModule(d_model, conv_kernel_size, dropout)
        self.ff2 = FeedForward(d_model, d_ff, dropout)

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        self.norm4 = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # Feed forward 1
        x = x + 0.5 * self.dropout(self.ff1(self.norm1(x)))

        # Multi-head attention
        x = x + self.dropout(self.mha(self.norm2(x), self.norm2(x), self.norm2(x)))

        # Convolution
        x = x + self.dropout(self.conv(self.norm3(x)))

        # Feed forward 2
        x = x + 0.5 * self.dropout(self.ff2(self.norm4(x)))

        return x

class EEGConformerClassifier(nn.Module):
    def __init__(self, num_classes, seq_len, in_channels, d_model=256, num_heads=8,
                 num_layers=4, d_ff=1024, dropout=0.1):
        super().__init__()

        # Input projection
        self.input_projection = nn.Conv1d(in_channels, d_model, kernel_size=3, padding=1)

        # Positional encoding
        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, d_model))

        # Conformer blocks
        self.conformer_blocks = nn.ModuleList([
            ConformerBlock(d_model, num_heads, d_ff, dropout=dropout)
            for _ in range(num_layers)
        ])

        # Classification head
        self.norm = nn.LayerNorm(d_model)
        self.global_pool = nn.AdaptiveAvgPool1d(1)
        self.classifier = nn.Sequential(
            nn.Linear(d_model, d_model // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, num_classes)
        )

    def forward(self, x):
        # x: (batch, channels, seq_len)
        batch_size = x.size(0)

        # Input projection
        x = self.input_projection(x)  # (batch, d_model, seq_len)
        x = x.transpose(1, 2)  # (batch, seq_len, d_model)

        # Add positional encoding
        x = x + self.pos_encoding

        # Apply conformer blocks
        for block in self.conformer_blocks:
            x = block(x)

        # Normalization
        x = self.norm(x)

        # Global pooling and classification
        x = x.transpose(1, 2)  # (batch, d_model, seq_len)
        x = self.global_pool(x).squeeze(-1)  # (batch, d_model)
        x = self.classifier(x)

        return x

# Pre-training for EEG representation learning
class EEGPreTrainingModel(nn.Module):
    def __init__(self, seq_len, in_channels, d_model=256, num_heads=8,
                 num_layers=4, d_ff=1024, dropout=0.1):
        super().__init__()

        # Input projection
        self.input_projection = nn.Conv1d(in_channels, d_model, kernel_size=3, padding=1)

        # Positional encoding
        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, d_model))

        # Conformer blocks
        self.conformer_blocks = nn.ModuleList([
            ConformerBlock(d_model, num_heads, d_ff, dropout=dropout)
            for _ in range(num_layers)
        ])

        # Pre-training heads
        self.norm = nn.LayerNorm(d_model)
        self.reconstruction_head = nn.Linear(d_model, in_channels)
        self.contrastive_head = nn.Linear(d_model, 128)

    def forward(self, x, return_features=False):
        # x: (batch, channels, seq_len)
        batch_size = x.size(0)

        # Input projection
        x_proj = self.input_projection(x)  # (batch, d_model, seq_len)
        x_proj = x_proj.transpose(1, 2)  # (batch, seq_len, d_model)

        # Add positional encoding
        x_proj = x_proj + self.pos_encoding

        # Apply conformer blocks
        features = x_proj
        for block in self.conformer_blocks:
            features = block(features)

        # Normalization
        features = self.norm(features)

        if return_features:
            return features

        # Reconstruction
        reconstruction = self.reconstruction_head(features)  # (batch, seq_len, in_channels)
        reconstruction = reconstruction.transpose(1, 2)  # (batch, in_channels, seq_len)

        # Contrastive features
        contrastive = self.contrastive_head(features.mean(dim=1))  # (batch, 128)

        return reconstruction, contrastive

class ImageEncoder(nn.Module):
    def __init__(self, embed_dim=256, pretrained=True):
        super().__init__()
        self.backbone = resnet18(weights=ResNet18_Weights.DEFAULT)
        self.backbone.fc = nn.Linear(self.backbone.fc.in_features, embed_dim)
        self.embed_dim = embed_dim

    def forward(self, x):
        return F.normalize(self.backbone(x), dim=-1)

class EEGEncoder(nn.Module):
    def __init__(self, seq_len, in_channels, embed_dim=256, d_model=256, num_heads=8,
                 num_layers=4, d_ff=1024, dropout=0.1):
        super().__init__()

        self.embed_dim = embed_dim

        # Input projection
        self.input_projection = nn.Conv1d(in_channels, d_model, kernel_size=3, padding=1)

        # Positional encoding
        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, d_model))

        # Conformer blocks
        self.conformer_blocks = nn.ModuleList([
            ConformerBlock(d_model, num_heads, d_ff, dropout=dropout)
            for _ in range(num_layers)
        ])

        # Classification head
        self.norm = nn.LayerNorm(d_model)
        self.global_pool = nn.AdaptiveAvgPool1d(1)
        self.projection = nn.Linear(d_model, embed_dim)

    def forward(self, x):
        # x: (batch, channels, seq_len)
        batch_size = x.size(0)

        # Input projection
        x = self.input_projection(x)  # (batch, d_model, seq_len)
        x = x.transpose(1, 2)  # (batch, seq_len, d_model)

        # Add positional encoding
        x = x + self.pos_encoding

        # Apply conformer blocks
        for block in self.conformer_blocks:
            x = block(x)

        # Normalization
        x = self.norm(x)

        x = x.transpose(1, 2)  # (batch, d_model, seq_len)
        x = self.global_pool(x).squeeze(-1)  # (batch, d_model)
        x = self.projection(x)
        x = F.normalize(x, dim=-1)

        return x

class EEGImageCLIP(nn.Module):
    def __init__(self, seq_len, in_channels, embed_dim=256, temperature=0.07):
        super().__init__()
        self.eeg_encoder = EEGEncoder(seq_len, in_channels, embed_dim)
        self.image_encoder = ImageEncoder(embed_dim)
        self.temperature = temperature

    def forward(self, eeg, images=None):
        eeg_features = self.eeg_encoder(eeg)

        if images is not None:
            image_features = self.image_encoder(images)
            return eeg_features, image_features

        return eeg_features

"""## 4.訓練実行"""

def pretrain_model(model, train_loader, val_loader, epochs=20, lr=1e-4):
    """Pre-train the model using reconstruction and contrastive learning"""
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    model.train()
    best_loss = float('inf')

    for epoch in range(epochs):
        total_loss = 0
        total_recon_loss = 0
        total_contrast_loss = 0

        for batch_idx, (X, y, subject_idxs) in enumerate(tqdm(train_loader, desc=f"Pre-training Epoch {epoch+1}")):
            X = X.to("cuda")

            # Add noise for denoising autoencoder
            noise = torch.randn_like(X) * 0.1
            X_noisy = X + noise

            # Forward pass
            reconstruction, contrastive = model(X_noisy)

            # Reconstruction loss
            recon_loss = F.mse_loss(reconstruction, X)

            # Contrastive loss (InfoNCE-like)
            batch_size = contrastive.size(0)
            if batch_size > 1:
                # Positive pairs: same subject
                labels = subject_idxs.to("cuda")
                similarity_matrix = torch.mm(contrastive, contrastive.t())

                # Create mask for positive pairs
                pos_mask = (labels.unsqueeze(0) == labels.unsqueeze(1)).float()
                pos_mask.fill_diagonal_(0)  # Remove self-similarity

                # Compute contrastive loss
                if pos_mask.sum() > 0:
                    pos_sim = similarity_matrix * pos_mask
                    neg_sim = similarity_matrix * (1 - pos_mask)

                    contrast_loss = -torch.log(
                        torch.exp(pos_sim).sum(dim=1) /
                        (torch.exp(pos_sim).sum(dim=1) + torch.exp(neg_sim).sum(dim=1) + 1e-8)
                    ).mean()
                else:
                    contrast_loss = torch.tensor(0.0, device=X.device)
            else:
                contrast_loss = torch.tensor(0.0, device=X.device)

            # Total loss
            loss = recon_loss + 0.1 * contrast_loss

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            total_recon_loss += recon_loss.item()
            total_contrast_loss += contrast_loss.item()

        scheduler.step()

        avg_loss = total_loss / len(train_loader)
        avg_recon_loss = total_recon_loss / len(train_loader)
        avg_contrast_loss = total_contrast_loss / len(train_loader)

        print(f"Epoch {epoch+1}/{epochs} | "
              f"Loss: {avg_loss:.4f} | "
              f"Recon: {avg_recon_loss:.4f} | "
              f"Contrast: {avg_contrast_loss:.4f}")

        if avg_loss < best_loss:
            best_loss = avg_loss
            cprint("New pretrained model saved. ")
            torch.save(model.state_dict(), "pretrained_model_v5.pt")

    return model

import json

def save_scores(scores, path="fold_scores.json"):
    with open(path, "w") as f:
        json.dump(scores, f)

def load_scores(path="fold_scores.json"):
    if os.path.exists(path):
        with open(path, "r") as f:
            return json.load(f)

    return {}

def create_finetuning_model(pretrained_model, num_classes, dropout=0.1, freeze_encoder=False, num_layers=None):
    """Create fine-tuning model from pre-trained model"""

    # Extract encoder components
    finetuning_model = EEGConformerClassifier(
        num_classes=num_classes,
        seq_len=100,
        in_channels=17,
        d_model=256,
        num_heads=8,
        num_layers=num_layers,
        d_ff=1024,
        dropout=dropout
    )

    # Load pre-trained weights
    pretrained_state = pretrained_model.state_dict()
    finetuning_state = finetuning_model.state_dict()

    # Transfer weights for encoder components
    for name in finetuning_state.keys():
        if name in pretrained_state:
            finetuning_state[name] = pretrained_state[name]

    finetuning_model.load_state_dict(finetuning_state)

    # Freeze encoder if requested
    if freeze_encoder:
        for name, param in finetuning_model.named_parameters():
            if 'classifier' not in name:
                param.requires_grad = False

    return finetuning_model

def create_finetuning_model_from_clip(clip_model, num_classes, dropout=0.1, freeze_encoder=False, num_layers=None):
    """Create fine-tuning mode from CLIP model"""
    finetuning_model = EEGConformerClassifier(
		num_classes=num_classes,
		seq_len=100,
		in_channels=17,
		d_model=256,
		num_heads=8,
		num_layers=num_layers,
		d_ff=1024,
		dropout=dropout
	)

    clip_encoder_state = clip_model.eeg_encoder.state_dict()
    finetuning_state = finetuning_model.state_dict()

    for name in finetuning_state.keys():
        if name in clip_encoder_state:
            finetuning_state[name] = clip_encoder_state[name]
    finetuning_model.load_state_dict(finetuning_state)

    if freeze_encoder:
        for name, param in finetuning_model.named_parameters():
            if 'classifier' not in name:
                param.requires_grad = False

    return finetuning_model

def train_single_fold(fold_idx, model_idx, train_indices, val_indices, pretrained_model, num_layers, config, model_type, start_epoch=0):
    """Train a single fold"""
    print(f"Training fold {fold_idx + 1}, model {model_idx + 1}")

    best_val_acc = 0
    patience = 10
    patience_counter = 0

    checkpoint_path = f"model_fold_{fold_idx+1}_model_{model_idx+1}_last.pt"

    if model_type == 'clip':
        model = create_finetuning_model_from_clip(
            pretrained_model,
            num_classes=5,
            dropout=config.get('dropout', 0.1),
            num_layers=num_layers
        ).to("cuda")
    else:
        model = create_finetuning_model(
            pretrained_model,
            num_classes=5,
            dropout=config.get('dropout', 0.1),
            num_layers=num_layers
        ).to("cuda")

    optimizer = torch.optim.AdamW([
        {'params': [p for n, p in model.named_parameters() if 'classifier' not in n],
         'lr': config['finetune_lr'], 'weight_decay': 0.01},
        {'params': [p for n, p in model.named_parameters() if 'classifier' in n],
         'lr': config['finetune_lr'] * 5, 'weight_decay': 0.001}
    ], eps=1e-8)

    scheduler = CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-7)

    if start_epoch > 0 and os.path.exists(checkpoint_path):
        checkpoint = torch.load(checkpoint_path)
        model.load_state_dict(checkpoint["model"])
        optimizer.load_state_dict(checkpoint["optimizer"])
        scheduler.load_state_dict(checkpoint["scheduler"])
        best_val_acc = checkpoint["best_val_acc"]
        patience_counter = checkpoint["patience_counter"]
        print(f"[Fold {fold_idx+1}] Resuming from epoch {start_epoch}")

    train_fold_set = ThingsEEGDataset(
        "train",
        augment=True,
        fold_indices=train_indices,
    )
    val_fold_set = ThingsEEGDataset(
        "train",
        augment=False,
        fold_indices=val_indices,
    )

    train_loader = torch.utils.data.DataLoader(
        train_fold_set, batch_size=config['batch_size'], shuffle=True
    )
    val_loader = torch.utils.data.DataLoader(
        val_fold_set, batch_size=config['batch_size'], shuffle=False
    )

    def accuracy(y_pred, y):
        return (y_pred.argmax(dim=-1) == y).float().mean()

    for epoch in range(start_epoch, config['finetune_epochs']):
        model.train()
        train_loss, train_acc = [], []

        for X, y, subject_idxs in tqdm(train_loader, desc=f"Fold {fold_idx+1} Epoch {epoch+1}"):
            X, y = X.to("cuda"), y.to("cuda")

            y_pred = model(X)
            loss = F.cross_entropy(y_pred, y)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            train_loss.append(loss.item())
            train_acc.append(accuracy(y_pred, y).item())

        model.eval()
        val_loss, val_acc = [], []

        for X, y, subject_idxs in val_loader:
            X, y = X.to("cuda"), y.to("cuda")

            with torch.no_grad():
                y_pred = model(X)

            val_loss.append(F.cross_entropy(y_pred, y).item())
            val_acc.append(accuracy(y_pred, y).item())

        scheduler.step()

        train_acc_avg = np.mean(train_acc)
        val_acc_avg = np.mean(val_acc)

        print(f"Fold {fold_idx+1} Epoch {epoch+1}: "
              f"train_acc: {train_acc_avg:.3f}, val_acc: {val_acc_avg:.3f}")

        if val_acc_avg > best_val_acc:
            best_val_acc = val_acc_avg
            patience_counter = 0
            torch.save(model.state_dict(), f"model_fold_{fold_idx+1}_model_{model_idx+1}_best.pt")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"Early stopping for fold {fold_idx+1}")
                break
        torch.save({
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_val_acc": best_val_acc,
            "patience_counter": patience_counter,
        }, checkpoint_path)

    model.load_state_dict(torch.load(f"model_fold_{fold_idx+1}_model_{model_idx+1}_best.pt"))
    return model, best_val_acc

def train_hierarchical_ensemble(k_folds=5, start_fold=0, start_model=0, start_epoch=0, score_path="conformer_v7_scores.json"):
    """Train hierarchical ensemble with different pretrained models"""

    # Define different models
    model_configs = [
		{'type': '6layer_pretrain', 'count': 1, 'path': 'pretrained_model_6layer.pt', 'num_layers': 6},
		{'type': '4layer_pretrain', 'count': 1, 'path': 'pretrained_model_4layer.pt', 'num_layers': 4},
		{'type': '4layer_clip', 'count': 1, 'path': 'pretrained_model_4layer_clip.pt', 'num_layers': 4},
	]

    # Define training configuration for each model type
    type_configs = {
		'6layer_pretrain':[
			{'batch_size': 112, 'finetune_lr': 3e-5, 'finetune_epochs': 50, 'dropout': 0.18},
		],
		'4layer_pretrain':[
			{'batch_size': 128, 'finetune_lr': 3e-5, 'finetune_epochs': 50, 'dropout': 0.1},
		],
		'4layer_clip': [
            {'batch_size':128, 'finetune_lr': 2e-5, 'finetune_epochs': 50, 'dropout': 0.15},
        ]
	}

    full_train_set = ThingsEEGDataset("train", augment=False)
    kfold = KFold(n_splits=k_folds, shuffle=True, random_state=42)

    all_models = []
    fold_scores = load_scores(score_path)

    model_list = []
    for config in model_configs:
        for i in range(config['count']):
            model_list.append({
				'type': config['type'],
				'path': config['path'],
				'num_layers': config['num_layers'],
				'instance_idx': i
			})
    for fold_idx, (train_indices, val_indices) in enumerate(kfold.split(range(len(full_train_set)))):
        current_start_model = start_model if fold_idx == start_fold else 0

        if fold_idx < start_fold:
            print(f"[Fold {fold_idx+1}] skipped (already completed)")
            continue

        fold_models = []

        for model_idx, model_info in enumerate(model_list):
            if fold_idx == start_fold and model_idx < start_model:
                print(f"[Fold {fold_idx+1} Model {model_idx+1}] skipped (already  completed)")
                continue
            print(f"\n=== Training Fold{fold_idx+1}, Model {model_idx+1}/{len(model_list)} ({model_info['type']}) ===")

            if model_info['type'] == '4layer_clip':
                clip_model = EEGImageCLIP(
                    seq_len=100,
                    in_channels=17,
                    embed_dim=256
                ).to("cuda")
                clip_model.load_state_dict(torch.load(model_info['path']))
                pretrained_model = clip_model
                model_type = 'clip'
            else:
                if model_info['num_layers'] == 6:
                    pretrained_model = EEGPreTrainingModel(
                        seq_len=100, in_channels=17, d_model=256, num_heads=8,
                        num_layers=6, d_ff=1024, dropout=0.15
                    ).to("cuda")
                else:
                    pretrained_model = EEGPreTrainingModel(
                        seq_len=100, in_channels=17, d_model=256, num_heads=8,
                        num_layers=4, d_ff=1024, dropout=0.15
                    ).to("cuda")

                pretrained_model.load_state_dict(torch.load(model_info['path']))
                model_type = 'pretrained'

            config = type_configs[model_info['type']][model_info['instance_idx']]
            current_start_epoch = start_epoch if fold_idx == start_fold else 0

            model, val_acc = train_single_fold(
                fold_idx, model_idx, train_indices, val_indices,
                pretrained_model, model_info['num_layers'], config, model_type=model_type, start_epoch=current_start_epoch
            )

            fold_models.append(model)

            score_key = f"fold_{fold_idx}_model_{model_idx}"
            fold_scores[score_key] = val_acc
            save_scores(fold_scores, score_path)

        all_models.append(fold_models)
        print(f"Fold {fold_idx+1} completed with {len(fold_models)} models")

    return all_models, fold_scores

# models, fold_scores_dict = train_hierarchical_ensemble(k_folds=5, start_fold=4, start_model=2, start_epoch=46)

# fold_scores = list(fold_scores_dict.values())

# print(f"\nFinal Results:")
# print(f"Average CV Score: {np.mean(fold_scores):.4f} +- {np.std(fold_scores):.4f}")
# print(f"Best Fold Score: {np.max(fold_scores):.4f}")
# print(f"Worst Fold Score: {np.min(fold_scores):.4f}")

# print(f"\nDetailed Scores:")
# for key, score in fold_scores_dict.items():
#     print(f"{key}: {score:.4f}")

fold_scores_dict = {
    'fold_1_model_1': 0.5052,
    'fold_1_model_2': 0.5018,
    'fold_1_model_3': 0.5008,
    'fold_2_model_1': 0.5041,
    'fold_2_model_2': 0.4966,
    'fold_2_model_3': 0.4949,
    'fold_3_model_1': 0.5082,
    'fold_3_model_2': 0.4963,
    'fold_3_model_3': 0.4944,
    'fold_4_model_1': 0.5043,
    'fold_4_model_2': 0.5022,
    'fold_4_model_3': 0.4951,
    'fold_5_model_1': 0.4974,
    'fold_5_model_2': 0.4878,
    'fold_5_model_3': 0.4900,
}

"""## 5.評価"""

def ensemble_predict(threshold_models, additional_models, test_loader, method='soft_voting'):
    """Enhanced ensemble prediction with threshold models + additional pretrained models"""
    all_predictions = []

    # Handle threshold models (tuple format: (model, fold, model_idx))
    print("Processing threshold-selected models:")
    for i, model_tuple in enumerate(threshold_models):
        model, fold, model_idx = model_tuple
        model.eval()
        model.to("cuda")
        predictions = []

        print(f"Generating predictions for threshold model {i+1}/{len(threshold_models)} (Fold {fold+1}, Model {model_idx+1})")

        with torch.no_grad():
            for X, subject_idxs in tqdm(test_loader, desc=f"Threshold Model {i+1}"):
                X = X.to("cuda")
                pred = model(X)

                if method == 'soft_voting':
                    pred = F.softmax(pred, dim=1)

                predictions.append(pred.cpu())

        predictions = torch.cat(predictions, dim=0)
        all_predictions.append(predictions)

    # Handle additional pretrained models
    print("\nProcessing additional pretrained models:")
    for i, model in enumerate(additional_models):
        model.eval()
        model.to("cuda")
        predictions = []

        print(f"Generating predictions for additional model {i+1}/{len(additional_models)}")

        with torch.no_grad():
            for X, subject_idxs in tqdm(test_loader, desc=f"Additional Model {i+1}"):
                X = X.to("cuda")
                pred = model(X)

                if method == 'soft_voting':
                    pred = F.softmax(pred, dim=1)

                predictions.append(pred.cpu())

        predictions = torch.cat(predictions, dim=0)
        all_predictions.append(predictions)

    # アンサンブル予測を計算
    ensemble_pred = torch.stack(all_predictions).mean(dim=0)

    total_models = len(threshold_models) + len(additional_models)
    print(f"\nEnsemble complete: {len(threshold_models)} threshold models + {len(additional_models)} additional models = {total_models} total models")

    return ensemble_pred.numpy()

model_configs = [
    {'type': '6layer_pretrain', 'count': 1, 'path': 'pretrained_model_6layer.pt', 'num_layers': 6},
    {'type': '4layer_pretrain', 'count': 1, 'path': 'pretrained_model_4layer.pt', 'num_layers': 4},
    {'type': '4layer_clip', 'count': 1, 'path': 'pretrained_model_4layer_clip.pt', 'num_layers': 4},
]

def load_all_trained_models(k_folds=5, model_configs=None):
    """Load all trained models from saved checkpoints"""

    if model_configs is None:
        # Default model configurations (same as in train_hierarchical_ensemble)
        model_configs = [
            {'type': '6layer_pretrain', 'count': 1, 'path': 'pretrained_model_6layer.pt', 'num_layers': 6},
            {'type': '4layer_pretrain', 'count': 1, 'path': 'pretrained_model_4layer.pt', 'num_layers': 4},
            {'type': '4layer_clip', 'count': 1, 'path': 'pretrained_model_4layer_clip.pt', 'num_layers': 4},
        ]

    # Create model list (same as in train_hierarchical_ensemble)
    model_list = []
    for config in model_configs:
        for i in range(config['count']):
            model_list.append({
                'type': config['type'],
                'path': config['path'],
                'num_layers': config['num_layers'],
                'instance_idx': i
            })

    all_models = []

    for fold_idx in range(k_folds):
        print(f"Loading models for fold {fold_idx + 1}")
        fold_models = []

        for model_idx, model_info in enumerate(model_list):
            # Load the pretrained model first
            if model_info['type'] == '4layer_clip':
                clip_model = EEGImageCLIP(
                    seq_len=100,
                    in_channels=17,
                    embed_dim=256
                ).to("cuda")
                clip_model.load_state_dict(torch.load(model_info['path']))
                pretrained_model = clip_model
                model_type = 'clip'
            else:
                if model_info['num_layers'] == 6:
                    pretrained_model = EEGPreTrainingModel(
                        seq_len=100, in_channels=17, d_model=256, num_heads=8,
                        num_layers=6, d_ff=1024, dropout=0.15
                    ).to("cuda")
                else:
                    pretrained_model = EEGPreTrainingModel(
                        seq_len=100, in_channels=17, d_model=256, num_heads=8,
                        num_layers=4, d_ff=1024, dropout=0.15
                    ).to("cuda")

                pretrained_model.load_state_dict(torch.load(model_info['path']))
                model_type = 'pretrained'

            # Create finetuning model
            if model_type == 'clip':
                model = create_finetuning_model_from_clip(
                    pretrained_model,
                    num_classes=5,
                    dropout=0.1,  # Default dropout
                    num_layers=model_info['num_layers']
                ).to("cuda")
            else:
                model = create_finetuning_model(
                    pretrained_model,
                    num_classes=5,
                    dropout=0.1,  # Default dropout
                    num_layers=model_info['num_layers']
                ).to("cuda")

            # Load the best trained weights
            checkpoint_path = f"model_fold_{fold_idx+1}_model_{model_idx+1}_best.pt"

            if os.path.exists(checkpoint_path):
                model.load_state_dict(torch.load(checkpoint_path))
                print(f"Loaded model from {checkpoint_path}")
            else:
                print(f"Warning: Checkpoint {checkpoint_path} not found!")

            fold_models.append(model)

        all_models.append(fold_models)
        print(f"Fold {fold_idx + 1} loaded with {len(fold_models)} models")

    return all_models

# # ------------------
# #    Dataloader
# # ------------------
test_set = ThingsEEGDataset("test")
test_loader = torch.utils.data.DataLoader(
    test_set, batch_size=128, shuffle=False
)

# # models
# loaded_models = load_all_trained_models(k_folds=5, model_configs=model_configs)
# flat_models = [model for fold in loaded_models for model in fold]
# print(len(flat_models))

# # ------------------
# #  Start evaluation
# # ------------------
# preds = ensemble_predict(flat_models, test_loader, method='soft_voting')
# np.save("submission", preds)
# print(f"Submission {preds.shape} saved.")

def load_scores(score_path):
    """Load scores from JSON file"""
    import json
    if os.path.exists(score_path):
        with open(score_path, 'r') as f:
            return json.load(f)
    return {}

def load_selective_models(k_folds=5, model_configs=None, selection_strategy='best_type', threshold=0.500):
    """Load models with selective strategy based on performance"""

    # Load scores
    # fold_scores = load_scores("conformer_v7_scores.json")

    if selection_strategy == 'best_type':
        # Only use model_0 (6layer) which consistently performs best
        selected_model_indices = [0]
        print("Strategy: Best Type Only (6-layer models)")
    elif selection_strategy == 'threshold':
        # Use individual model weights with score > threshold
        selected_model_indices = []

        print(f"Strategy: Individual Weight Threshold (>{threshold})")
        print("Checking individual model weights:")

        for fold in range(k_folds):
            for model_idx in range(3):
                score = fold_scores_dict[f"fold_{fold+1}_model_{model_idx+1}"]
                print(f"  Fold {fold+1} Model {model_idx+1}: {score:.4f}", end="")

                if score > threshold:
                    selected_model_indices.append((fold, model_idx))
                    print("  Selected")
                else:
                    print("  Rejected")

    print(f"Selected (fold, model) pairs: {selected_model_indices}")
    print(f"Total selected weights: {len(selected_model_indices)}")

    # Load all models first
    all_models = load_all_trained_models(k_folds, model_configs)

    # For threshold strategy, we need to handle individual weights differently
    if selection_strategy == 'threshold':
        # Return models with their fold and model index information
        selected_models = []
#         print(selected_model_indices)
        for fold, model_idx in selected_model_indices:
            selected_models.append((all_models[fold][model_idx], fold, model_idx))
        return selected_models, selected_model_indices
    else:
        # Filter to selected models only (for best_type strategy)
        selected_models = []
        for fold_models in all_models:
            selected_fold_models = [fold_models[i] for i in selected_model_indices]
            selected_models.append(selected_fold_models)
        return selected_models, selected_model_indices

from zipfile import ZipFile
import os

def create_submission_zip(submission_name, model_indices=None):
    """Create submission zip file with required models"""

    # Base files
    notebook_path = "DLBasics2025_competition_EEG_conformer_v7.ipynb"

    # All model paths
    all_model_paths = []
    for fold in range(1, 6):
        for model in range(1, 4):
            all_model_paths.append(f"model_fold_{fold}_model_{model}_best.pt")

    if model_indices is not None:
        if model_indices and isinstance(model_indices[0], tuple):
            model_paths_to_include = []
            for fold, model_idx in model_indices:
                model_path = f"model_fold_{fold+1}_model_{model_idx+1}_best.pt"
                model_paths_to_include.append(model_path)
            print(f"Using threshold-based selection: {len(model_indices)} specific models")
        else:
            filtered_model_paths = []
            for fold in range(1, 6):
                for model_idx in model_indices:
                    filtered_model_paths.append(f"model_fold_{fold}_model_{model_idx+1}_best.pt")
            model_paths_to_include = filtered_model_paths
            print(f"Using type-based selection: {len(model_indices)} model types across all folds")
    else:
        model_paths_to_include = all_model_paths
        print("Using all models")

    with ZipFile(f"{submission_name}.zip", "w") as zf:
        zf.write(f"submission.npy")

        # Add selected model files
        added_models = 0
        for model_path in model_paths_to_include:
            if os.path.exists(model_path):
                zf.write(model_path)
                added_models += 1
            else:
                print(f"Warning: {model_path} not found")

        # Add notebook
        if os.path.exists(notebook_path):
            zf.write(notebook_path)
            print(f"Added notebook: {notebook_path}")

    print(f"Created {submission_name}.zip with {added_models} model files")

    if model_indices and isinstance(model_indices[0], tuple):
        print("Selected models:")
        for fold, model_idx in model_indices:
            print(f"  - Fold {fold+1}, Model {model_idx+1}")

    return f"{submission_name}.zip"

def load_additional_pretrained_models():
    """Load additional pretrained models for ensemble"""
    additional_models = []

    additional_model_paths = [
        {'pretrained_path': 'pretrained_model_6layer.pt', 'path': 'additional_6layer_model.pt', 'num_layers': 6, 'type': '6layer_pretrain'},
        {'pretrained_path': 'pretrained_model_4layer.pt', 'path': 'additional_4layer_model.pt', 'num_layers': 4, 'type': '4layer_pretrain'},
        {'pretrained_path': 'pretrained_model_6layer.pt', 'path': 'additional_6layer_model_2.pt', 'num_layers': 6, 'type': '6layer_pretrain'},
    ]

    for i, model_info in enumerate(additional_model_paths):
        print(f"Loading additional model {i+1}: {model_info['path']}")

        if model_info['num_layers'] == 6:
            pretrained_model = EEGPreTrainingModel(
                seq_len=100, in_channels=17, d_model=256, num_heads=8,
                num_layers=6, d_ff=1024, dropout=0.15
            ).to("cuda")
        else:
            pretrained_model = EEGPreTrainingModel(
                seq_len=100, in_channels=17, d_model=256, num_heads=8,
                num_layers=4, d_ff=1024, dropout=0.15
            ).to("cuda")

        pretrained_model.load_state_dict(torch.load(model_info['pretrained_path']))

        model = create_finetuning_model(
            pretrained_model,
            num_classes=5,
            dropout=0.1,
            num_layers=model_info['num_layers']
        ).to("cuda")

        model.load_state_dict(torch.load(model_info['path']))

        additional_models.append(model)
        print(f"Successfully loaded additional model {i+1}")

    return additional_models

threshold_models, threshold_indices = load_selective_models(
    k_folds=5,
    model_configs=model_configs,
    selection_strategy='threshold',
    threshold=0.500
)

additional_models = load_additional_pretrained_models()

print(f"Threshold models: {len(threshold_models)}")
print(f"Additional models: {len(additional_models)}")
print(f"Total models: {len(threshold_models) + len(additional_models)}")

print("Generating predictions for Threshold-based...")
preds_threshold = ensemble_predict(threshold_models, additional_models, test_loader, method='soft_voting')
np.save("submission", preds_threshold)
create_submission_zip("submission_threshold", threshold_indices)

"""## 提出方法

以下の3点をzip化し，Omnicampusの「最終課題 (EEG)」から提出してください．

- `submission.npy`
- `model_last.pt`や`model_best.pt`など，テストに使用した重み（拡張子は`.pt`のみ）
- 本Colab Notebook
"""

# from zipfile import ZipFile

# model_path1 = "model_fold_1_model_1_best.pt"
# model_path2 = "model_fold_1_model_2_best.pt"
# model_path3 = "model_fold_1_model_3_best.pt"
# model_path4 = "model_fold_2_model_1_best.pt"
# model_path5 = "model_fold_2_model_2_best.pt"
# model_path6 = "model_fold_2_model_3_best.pt"
# model_path7 = "model_fold_3_model_1_best.pt"
# model_path8 = "model_fold_3_model_2_best.pt"
# model_path9 = "model_fold_3_model_3_best.pt"
# model_path10 = "model_fold_4_model_1_best.pt"
# model_path11 = "model_fold_4_model_2_best.pt"
# model_path12 = "model_fold_4_model_3_best.pt"
# model_path13 = "model_fold_5_model_1_best.pt"
# model_path14 = "model_fold_5_model_2_best.pt"
# model_path15 = "model_fold_5_model_3_best.pt"
# notebook_path = "DLBasics2025_competition_EEG_conformer_v7.ipynb"

# with ZipFile("submission.zip", "w") as zf:
#     zf.write("submission.npy")
#     zf.write(model_path1)
#     zf.write(model_path2)
#     zf.write(model_path3)
#     zf.write(model_path4)
#     zf.write(model_path5)
#     zf.write(model_path6)
#     zf.write(model_path7)
#     zf.write(model_path8)
#     zf.write(model_path9)
#     zf.write(model_path10)
#     zf.write(model_path11)
#     zf.write(model_path12)
#     zf.write(model_path13)
#     zf.write(model_path14)
#     zf.write(model_path15)
#     zf.write(notebook_path)

