# -*- coding: utf-8 -*-
"""data_download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRwY1z_tJb9M9rNFQI10iwEWg5IBxceZ

# Deep Learning 基礎講座 最終課題: 脳波分類 データダウンロード用

- 下記の notebook を実行することで，最終課題の 脳波分類 コンペティションに利用するデータが作成されます．
- 実行時のランタイムは CPU で問題ございません．
- データのダウンロードと分割に 30 分ほどかかることを確認しています．
- **スクリプト内で 1 度オリジナルのデータをダウンロードしています．サーバー負荷を考慮して可能な限り複数回の実行はお控えください．**
"""

# omnicampus の演習環境用
!pip install googledrivedownloader

# データのダウンロードと分割
import os
import subprocess
!pip install googledrivedownloader
from googledrivedownloader import download_file_from_google_drive

file_id = "1swwXVBcH2RJOJwtps2D0Fl5EBJQfeGeS" if "COLAB_" in "".join(os.environ.keys()) else "1O9QhJxP3U_rLKVKnJHR4vBAjAwhXbc4Z"
download_file_from_google_drive(
    file_id=file_id,
    dest_path='./dist.zip',
    unzip=True,
)
download_file_from_google_drive(
    file_id="1cpZ0JLgzQo1wGBxtULJB35RLqIjs_gxX",
    dest_path='./split_data.sh',
)
download_file_from_google_drive(
    file_id="1eQlnnbvaMtYPJxqqffdurcrjda7YmaOs",
    dest_path='./categorization.tsv',
)
download_file_from_google_drive(
    file_id="1LfmZMCukEqK7MuOPH_fjjbZvmw-IH3mC",
    dest_path='./category_mat_manual.tsv',
)

subprocess.run(["chmod", "+x", "dist/split_data.py"])
subprocess.run(["chmod", "+x", "split_data.sh"])
output = subprocess.run(["./split_data.sh"], capture_output=True, text=True)
print(output.stdout)

# google drive のマウント（Colabの場合）
from google.colab import drive
drive.mount('/content/drive')

# パスは保存したいディレクトリに適宜修正してください
!cp -r data /content/drive/MyDrive/DLBasic/final_project/

